spring:
  datasource:
    url: jdbc:h2:mem:impulse;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  flyway:
    enabled: false

jwt:
  secret: ${JWT_SECRET:demo-key-insegura-solo-para-demostracion-local-32-chars}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hora en milisegundos

logging:
  level:
    root: INFO
    '[com.impulse]': DEBUG

server:
  port: 8080

# Demo environment for IMPULSE - Solo para demostraciones locales
# En producción estas variables deben venir del sistema/vault
impulse:
  notifications:
    email-smtp-host: ${EMAIL_SMTP_HOST:smtp.gmail.com}
    email-smtp-port: ${EMAIL_SMTP_PORT:587}
    email-smtp-user: ${EMAIL_SMTP_USER:demo@impulse.com}
    email-smtp-pass: ${EMAIL_SMTP_PASS:demo-password}
    whatsapp-api-url: ${WHATSAPP_API_URL:https://api.whatsapp.demo.com}
    whatsapp-api-token: ${WHATSAPP_API_TOKEN:demo-token}
    telegram-bot-token: ${TELEGRAM_BOT_TOKEN:demo-bot-token}
    telegram-chat-id: ${TELEGRAM_CHAT_ID:demo-chat-id}
