# Configuraci칩n para entorno de desarrollo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/impulse?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
    username: impulse_app
    password: impulse_secure_2025!
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
  flyway:
    enabled: false

# Configuraci칩n JWT para entorno de desarrollo
jwt:
  # IMPORTANTE: En producci칩n usar variable de entorno JWT_SECRET con clave >= 32 caracteres
  secret: ${JWT_SECRET:dev-key-insegura-solo-para-desarrollo-local-cambiar-en-prod}
  expiration: 3600000 # 1 hora en milisegundos

# Logging m치s detallado para desarrollo
logging:
  level:
    '[com.impulse]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.flywaydb]': INFO
