// Frontend enums matching backend domain/enums exactly

export enum UserRole {
  ADMIN = "ADMIN",
  USER = "USER",
  COACH = "COACH",
  VALIDATOR = "VALIDATOR",
}

export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
}

export enum ChallengeCategory {
  FITNESS = "FITNESS",
  HEALTH = "HEALTH",
  EDUCATION = "EDUCATION",
  CREATIVITY = "CREATIVITY",
  SOCIAL = "SOCIAL",
  CAREER = "CAREER",
  FINANCE = "FINANCE",
  ENVIRONMENT = "ENVIRONMENT",
  TECHNOLOGY = "TECHNOLOGY",
  LIFESTYLE = "LIFESTYLE",
}

export enum ChallengeDifficulty {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
  EXPERT = "EXPERT",
}

export enum ChallengeStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  SUSPENDED = "SUSPENDED",
}

export enum ChallengeType {
  INDIVIDUAL = "INDIVIDUAL",
  TEAM = "TEAM",
  COMMUNITY = "COMMUNITY",
}

export enum ParticipationStatus {
  PENDING = "PENDING",
  ACTIVE = "ACTIVE",
  COMPLETED = "COMPLETED",
  WITHDRAWN = "WITHDRAWN",
  DISQUALIFIED = "DISQUALIFIED",
}

export enum EvidenceType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  DOCUMENT = "DOCUMENT",
  AUDIO = "AUDIO",
  LINK = "LINK",
  TEXT = "TEXT",
}

export enum EvidenceStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  UNDER_REVIEW = "UNDER_REVIEW",
}

export enum ValidationStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  REJECTED = "REJECTED",
  EXPIRED = "EXPIRED",
}

export enum ValidationDecision {
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  NEEDS_MORE_INFO = "NEEDS_MORE_INFO",
  ESCALATED = "ESCALATED",
}

export enum ValidationMethod {
  MANUAL = "MANUAL",
  AUTOMATIC = "AUTOMATIC",
  PEER_REVIEW = "PEER_REVIEW",
  AI_ASSISTED = "AI_ASSISTED",
}

export enum ValidationType {
  EVIDENCE_REVIEW = "EVIDENCE_REVIEW",
  COMPLETION_CHECK = "COMPLETION_CHECK",
  QUALITY_ASSESSMENT = "QUALITY_ASSESSMENT",
  COMPLIANCE_CHECK = "COMPLIANCE_CHECK",
}

export enum ValidationPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum ValidatorStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
  TRAINING = "TRAINING",
}

export enum ValidatorSpecialty {
  FITNESS = "FITNESS",
  HEALTH = "HEALTH",
  EDUCATION = "EDUCATION",
  TECHNOLOGY = "TECHNOLOGY",
  BUSINESS = "BUSINESS",
  CREATIVE = "CREATIVE",
  GENERAL = "GENERAL",
}

export enum CoachStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
  PENDING_APPROVAL = "PENDING_APPROVAL",
}

export enum CoachLevel {
  BEGINNER = "BEGINNER",
  INTERMEDIATE = "INTERMEDIATE",
  ADVANCED = "ADVANCED",
  EXPERT = "EXPERT",
  MASTER = "MASTER",
}

export enum RatingType {
  CHALLENGE = "CHALLENGE",
  COACH = "COACH",
  USER = "USER",
  CONTENT = "CONTENT",
}

export enum ValidationResult {
  PASS = "PASS",
  FAIL = "FAIL",
  PARTIAL = "PARTIAL",
  PENDING = "PENDING",
}

export enum DifficultyLevel {
  VERY_EASY = "VERY_EASY",
  EASY = "EASY",
  MEDIUM = "MEDIUM",
  HARD = "HARD",
  VERY_HARD = "VERY_HARD",
}

export enum ConfidenceLevel {
  VERY_LOW = "VERY_LOW",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  VERY_HIGH = "VERY_HIGH",
}

export enum RecommendedAction {
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  REQUEST_MORE_INFO = "REQUEST_MORE_INFO",
  ESCALATE = "ESCALATE",
  REVIEW_LATER = "REVIEW_LATER",
}

export enum NotificationType {
  CHALLENGE_CREATED = "CHALLENGE_CREATED",
  CHALLENGE_STARTED = "CHALLENGE_STARTED",
  CHALLENGE_COMPLETED = "CHALLENGE_COMPLETED",
  EVIDENCE_SUBMITTED = "EVIDENCE_SUBMITTED",
  EVIDENCE_VALIDATED = "EVIDENCE_VALIDATED",
  VALIDATION_REQUESTED = "VALIDATION_REQUESTED",
  VALIDATION_COMPLETED = "VALIDATION_COMPLETED",
  ACHIEVEMENT_UNLOCKED = "ACHIEVEMENT_UNLOCKED",
  REMINDER = "REMINDER",
  SYSTEM_ALERT = "SYSTEM_ALERT",
}

export enum InvitationStatus {
  PENDING = "PENDING",
  ACCEPTED = "ACCEPTED",
  DECLINED = "DECLINED",
  EXPIRED = "EXPIRED",
}

export enum ReportStatus {
  OPEN = "OPEN",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  DISMISSED = "DISMISSED",
  ESCALATED = "ESCALATED",
}

export enum ReportReason {
  INAPPROPRIATE_CONTENT = "INAPPROPRIATE_CONTENT",
  SPAM = "SPAM",
  HARASSMENT = "HARASSMENT",
  FAKE_EVIDENCE = "FAKE_EVIDENCE",
  CHEATING = "CHEATING",
  COPYRIGHT_VIOLATION = "COPYRIGHT_VIOLATION",
  OTHER = "OTHER",
}

export enum ReportPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum ActionTaken {
  WARNING_ISSUED = "WARNING_ISSUED",
  CONTENT_REMOVED = "CONTENT_REMOVED",
  USER_SUSPENDED = "USER_SUSPENDED",
  USER_BANNED = "USER_BANNED",
  NO_ACTION = "NO_ACTION",
  EVIDENCE_REJECTED = "EVIDENCE_REJECTED",
}

export enum AppealStatus {
  PENDING = "PENDING",
  UNDER_REVIEW = "UNDER_REVIEW",
  APPROVED = "APPROVED",
  DENIED = "DENIED",
}

export enum ContentType {
  CHALLENGE = "CHALLENGE",
  EVIDENCE = "EVIDENCE",
  COMMENT = "COMMENT",
  PROFILE = "PROFILE",
  MESSAGE = "MESSAGE",
}
