-- Phase 8: Validators & Validations
CREATE TABLE IF NOT EXISTS validators (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT NOT NULL,
  expertise VARCHAR(120),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS validations (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  reto_id BIGINT NOT NULL,
  validator_id BIGINT NOT NULL,
  status VARCHAR(24) NOT NULL,
  feedback TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
