spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/impulse?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid}
    username: ${DB_USER:impulse_app}
    password: ${DB_PASSWORD:impulse_secure_2025!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        '[format_sql]': true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  profiles:
    active: dev

# Configuración JWT (compatibilidad legacy)
jwt:
  secret: ${JWT_SECRET:impulse-enterprise-jwt-secret-key-256-bits-minimum-required-for-security}
  expiration: ${JWT_EXPIRATION:900000} # 15 minutos para tokens de acceso

# Variables de entorno para configuración empresarial
# FRONTEND_URL, PRODUCTION_MODE, COOKIE_SECURE, COOKIE_DOMAIN
      
logging:
  level:
    root: INFO
    '[com.impulse.common.security]': DEBUG # Debug para autenticación empresarial
