spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/impulse?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid}
    username: ${DB_USER:impulse_app}
    password: ${DB_PASSWORD:impulse_secure_2025!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        '[format_sql]': true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  profiles:
    active: dev

jwt:
  secret: ${JWT_SECRET:cambia-esto-por-un-secreto-seguro}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hora en milisegundos

logging:
  level:
    root: INFO
