# =============================================
# IMPULSE - Configuración de Logging
# Configuración completa de logs para auditoría, seguridad y compliance
# Autor: Sistema IMPULSE
# Fecha: 2025-08-07
# Versión: 1.0
# =============================================

# Configuración raíz de logging
logging:
  level:
    root: INFO
    com.impulse: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    
  # Configuración de appenders y patrones
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{user}] [%X{session}] [%X{ip}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{user}] [%X{session}] [%X{ip}] [%X{action}] %logger{36} - %msg%n"

  # Configuración de archivos de log
  file:
    name: logs/impulse-application.log
    max-size: 50MB
    max-history: 30
    total-size-cap: 1GB

# Configuración específica por entorno
---
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    com.impulse: TRACE
    org.springframework.security: TRACE
  file:
    name: logs/dev/impulse-dev.log

---
spring:
  config:
    activate:
      on-profile: test

logging:
  level:
    root: WARN
    com.impulse: DEBUG
  file:
    name: logs/test/impulse-test.log

---
spring:
  config:
    activate:
      on-profile: prod

logging:
  level:
    root: WARN
    com.impulse: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: WARN
  file:
    name: logs/prod/impulse-prod.log
    max-size: 100MB
    max-history: 90
    total-size-cap: 5GB

# =============================================
# Configuración avanzada de logback (logback-spring.xml embebida)
# =============================================

# Logs de auditoría separados
audit:
  logging:
    enabled: true
    file: logs/audit/impulse-audit.log
    level: INFO
    max-size: 100MB
    max-history: 365  # 1 año de retención
    total-size-cap: 10GB
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [AUDIT] [%X{user}] [%X{ip}] [%X{action}] [%X{result}] - %msg%n"

# Logs de seguridad separados
security:
  logging:
    enabled: true
    file: logs/security/impulse-security.log
    level: INFO
    max-size: 50MB
    max-history: 180  # 6 meses de retención
    total-size-cap: 2GB
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [SECURITY] [%X{user}] [%X{ip}] [%X{threat}] [%X{severity}] - %msg%n"

# Logs de acceso HTTP separados
access:
  logging:
    enabled: true
    file: logs/access/impulse-access.log
    level: INFO
    max-size: 200MB
    max-history: 30  # 1 mes de retención
    total-size-cap: 5GB
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [ACCESS] [%X{ip}] [%X{method}] [%X{uri}] [%X{status}] [%X{duration}] [%X{user}] - %msg%n"

# Logs de base de datos separados
database:
  logging:
    enabled: true
    file: logs/database/impulse-db.log
    level: INFO
    max-size: 100MB
    max-history: 60  # 2 meses de retención
    total-size-cap: 3GB
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [DATABASE] [%X{user}] [%X{operation}] [%X{table}] [%X{duration}] - %msg%n"

# Logs de errores críticos separados
critical:
  logging:
    enabled: true
    file: logs/critical/impulse-critical.log
    level: ERROR
    max-size: 50MB
    max-history: 365  # 1 año de retención
    total-size-cap: 2GB
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [CRITICAL] [%X{user}] [%X{ip}] [%X{error_code}] [%X{module}] - %msg%n"

# =============================================
# Configuración de MDC (Mapped Diagnostic Context)
# =============================================
mdc:
  enabled: true
  clear-on-request-completion: true
  fields:
    - user_id
    - session_id
    - ip_address
    - user_agent
    - request_id
    - action_type
    - module_name
    - trace_id

# =============================================
# Configuración de alertas por logs críticos
# =============================================
alerts:
  critical_errors:
    enabled: true
    threshold: 5  # Número de errores críticos para activar alerta
    time_window: 300  # Ventana de tiempo en segundos (5 minutos)
    notification:
      email: security@impulse.dev
      slack: true
      sms: false

  security_events:
    enabled: true
    threshold: 3  # Número de eventos de seguridad para activar alerta
    time_window: 180  # Ventana de tiempo en segundos (3 minutos)
    notification:
      email: security@impulse.dev
      slack: true
      sms: true

# =============================================
# Configuración de limpieza automática de logs
# =============================================
cleanup:
  enabled: true
  schedule: "0 2 * * *"  # Todos los días a las 2:00 AM
  retention:
    application: 30  # días
    audit: 365  # días
    security: 180  # días
    access: 30  # días
    database: 60  # días
    critical: 365  # días
  compression: true
  archive_path: logs/archive/

# =============================================
# Configuración de monitorización de logs
# =============================================
monitoring:
  enabled: true
  metrics:
    log_count_per_level: true
    log_size_tracking: true
    error_rate_tracking: true
    performance_tracking: true
  export:
    prometheus: true
    grafana: true
    elasticsearch: false

# =============================================
# Configuración de compliance y GDPR
# =============================================
compliance:
  gdpr:
    log_anonymization: true
    pii_detection: true
    automatic_redaction: true
    retention_compliance: true
  audit_trail:
    immutable_logs: true
    digital_signature: false  # Para futuras versiones
    blockchain_integration: false  # Para futuras versiones
  legal:
    court_admissible: true
    evidence_chain: true
    forensic_ready: true
