name: Quality Gates

# Notes:
# - This workflow purposely avoids referencing repository secrets (e.g. CODECOV_TOKEN)
#   and external third-party actions at specific versions that some linters flag.
# - Coverage artifacts are uploaded as build artifacts. To re-enable Codecov, add
#   a separate step conditioned on the presence of the secret in the repository
#   (for example: `if: ${{ secrets.CODECOV_TOKEN != '' }}`) and ensure the secret
#   exists in GitHub Settings > Secrets.

on:
  push:
    branches: [ main, develop ]
  pull_request:

permissions:
  contents: read
  checks: write
  security-events: write

jobs:
  build:
    name: Build, test and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Frontend - install & test
        run: |
          cd frontend
          npm ci
          npm test -- --coverage --runInBand

      - name: Backend - build & test
        run: |
          cd backend
          ./mvnw -B -U clean verify

      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-reports
          path: |
            frontend/coverage
            backend/target/site/jacoco

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript', 'java' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Analyze
        uses: github/codeql-action/analyze@v2
