name: quality-gates
on:
  pull_request:
  push:
    branches: [ main, develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Backend Build & Tests
        run: |
          cd backend
          mvn -q clean verify
      - name: Event Schema Lint
        run: |
          while IFS= read -r line; do echo "$line"; done < docs/analytics/events-sample.ndjson | node tools/event-schema-lint.js
      - name: Anti-duplicados
        run: |
          node tools/check-rest-duplicates.js
          node tools/check-flyway-versions.js
          node tools/check-flags-sync.js
          node tools/check-event-taxonomy-sync.js
          node tools/check-file-size.js
      - name: Frontend Typecheck & Tests
        run: |
          cd frontend
          npm ci
          npm test -- --watchAll=false
      - name: Frontend Build (assurance)
        run: |
          cd frontend
          npm run build
